### ISSUE TITLE
get_partial and length

### ISSUE THREAD

**Issue by palainp** [yomimono/chamelon#9]
Hi, thank you a lot for this amazing work!

I just want to add a comment regarding the length with `get_partial`.
My intention with length was to indicate a maximum size that I'll be able to read, and so in the mirage_test, the line `Chamelon.get_partial fs key ~offset:0 ~length:(2 * (String.length content))` should give `Ok content`. This is what I noted as a short string, but it may be confusing :( And I don't wrote about that but the next test `Chamelon.get_partial fs key ~offset:x ~length:0` may returns `Ok ""` and it's fine for me (although this seems like a complete nonsense to call with `~length:0`)

So far I've written a wraper to get these results and I don't know if it's better to let the client check the file size of chamelon check the parameters.

**Comment by yomimono** [comment]
~~I was on the fence about what to do there myself, but went for the option that made `chamelon`'s job easier :sweat_smile: Maybe we should discuss it over in the mirage-kv issue? It should be documented, whichever way we decide, since future implementers will surely have the same question.~~ I was wrong here, see comment below :sweat_smile:

**Comment by yomimono** [comment]
On re-reading the docstring at https://github.com/mirage/mirage-kv/pull/28/files#diff-8ab444171da07eb598c0b532bb11532c9e8f7d4f88ad76ad641d12806117df43R143 , it's actually pretty clear and I just misread/misinterpreted it! Next release will have a correct implementation.

**Comment by palainp** [comment]
It wasn't on the first version but @hannesm asked me to be more precise.

If it sounds better to check the parameters in get_partial and return errors, it may needs to add other types of error? I'm openned on way is the more useful interface.

And again thanks for tour work!

**Comment by yomimono** [comment]
> If it sounds better to check the parameters in get_partial and return errors, it may needs to add other types of error

I would *really* like a few more error types in `mirage-kv`. There are a bunch of situations where `chamelon` returns `Not_found (Mirage_kv.Key.empty)` for lack of `Corrupt`, for example.

**Comment by yomimono** [comment]
See what you think about commit e16753374662ca899cc67a627d064cf76427d86c , which I *think* does the right thing for `offset` > the file length.

**Comment by palainp** [comment]
I can confirm that with this patch on it works like a charm :) Thank you!

**Comment by yomimono** [comment]
Great! The fix is released in v0.1.2.
